### ISSUE TITLE
Segment trackEvent doesn't work right after CodePush update installs

### ISSUE THREAD

**Issue by YeshanJay** [segmentio/analytics-react-native#180] opened 2020-05-31 22:13 UTC
Our React Native project has both Segment and CodePush integrated.

Segment works fine, normally.

But there's a scenario where Segment stops working right after a CodePush update has been installed. Nothing gets flushed out and none of the events are shown in the Live Debugger list - except for events that are tracked in the native layer (eg: "Application Opened" and "Application Backgrounded" - only these show up).

So I assumed that any Segment call in the RN - Javascript layer only stops working after the app restarts the bundle (by CodePush).

The user should close and kill the app and reopen the app for it to work normally again.

Happens to both iOS and Android (when installed from the store).

And weirdly enough, I cannot recreate the issue on Android when I run a debug or release build directly to my Android phone from my machine (it just works 🤷‍♂️). Same goes for iOS simulators.

Any ideas or workarounds on this?

---

This is how the setup looks like:
```ts
import React, { Component } from "react";
import CodePush from "react-native-code-push";
import segment from "@segment/analytics-react-native";

...

class App extends Component {

    constructor(props) {
        super(props);

        this.setupSegment();
    }

    private setupSegment(): void {
        segment.setup("<Segment Write Key>", {
            debug: true,
            trackAppLifecycleEvents: true,
            ios: {
                trackAdvertising: true
            }
        });
    }

    ...
}

export default CodePush({
    installMode: CodePush.InstallMode.IMMEDIATE,
    checkFrequency: CodePush.CheckFrequency.ON_APP_RESUME,
    updateDialog: null
})(App);

```

```
react-native: 0.61.5
react-native-code-push: 6.1.0
@segment/analytics-react-native: 1.1.1-beta.2 (also tried 1.1.1-beta.5)
 ```

**Comment by bsneed** [comment] 2020-06-01 16:37
Hi @YeshanJay, thanks for filing this!  CodePush isn't something we've used/tested here internally.  On a quick glance of open issues at [here](https://github.com/Microsoft/react-native-code-push/issues?q=is%3Aopen+is%3Aissue), it looks like there's a number of issues around pieces of code no longer functioning correctly after a code push update.  There also appears to be some fixes sitting in their master tree around RN 0.62 and other compatibility improvements.  I'd recommend trying the latest bits.  code-push at 6.2.1, react-native at 0.62.

**Comment by viggyfresh** [comment] 2020-07-21 18:46
we're experiencing the same issue - with CodePush at 6.2.1 and RN at 0.61. @YeshanJay were you able to find a solution?

**Comment by YeshanJay** [comment] 2020-07-23 02:28
@viggyfresh Actually we are not in the position to do a version upgrade and check at the moment 😕. So what we decided to do was just deploy the builds manually.

The least thing we can do is to automate the builds at this point.

**Comment by bsneed** [comment] 2021-02-08 23:29
Please reopen if necessary.  Closing due to age.

**Closed by bsneed** 2021-02-08 23:29 UTC

**Comment by zeusstl** [comment] 2021-09-10 14:56
@viggyfresh or @YeshanJay Did you ever find a solution? Experiencing the same issue.

**Comment by viggyfresh** [comment] 2021-09-21 21:44
@zeusstl I tried to put together a repro repo for Segment to look at, but was unable to consistently reproduce the issue on a simulator or real device. so unfortunately no clear insights or solutions to offer :(
