### ISSUE TITLE
Setup fails with 'writeKey must not be null or empty'

### ISSUE THREAD

**Issue by danborthwick** [segmentio/analytics-react-native#290] opened 2021-03-29 05:18 UTC
Using @segment/analytics-react-native v1.4.3 and @segment/analytics-react-native-intercom v1.4.3.

We recently updated a seemingly unrelated library, react-native-purchases, to v4.1.0. With the update, our app shows a React Native red box on startup with the message _'writeKey must not be null or empty'_. 

``` 
CatalystInstanceImpl caught native exception
 java.lang.IllegalArgumentException: writeKey
 	at com.segment.analytics.Analytics$Builder.<init>(Analytics.java:108
 	at com.segment.analytics.Analytics.with(Analytics.java:175)
 	at com.segment.analytics.reactnative.core.RNAnalyticsModule
 	at com.segment.analytics.reactnative.core.RNAnalyticsModule.setup(RNAnalyticsModule.kt:207)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.facebook.react.bridge.JavaMethodWrapper.in
 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
 	at android.os.Handler.handleCallback(Handler.java:873)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at com.facebook.react.bridge.queue.MessageQueueThreadH
 	at android.os.Looper.loop(Looper.java:193)
 	at com.facebook.react.bridge.queue.Message
 	at java.lang.Thread.run(Thread.java:764)
 ````

Debugging `RNAnalyticsModule.setup()` confirms that `writeKey` is being passed with a valid value. It also reveals an IllegalStateException being caught and ignored (line 190). While the comment in that catch block reads _pass if the error is due to calling setSingletonInstance multiple times_. However, the exception has the message `java.lang.IllegalStateException: Method addObserver must be called on the main thread_`. So it would seem that setup()'s first attempt to initialise a client is silently failing, then when `analytics.track()` is called from `trackApplicationLifecycleEvents()`, a second attempt is made to initialise a client which fails, causing the red box error.
 
Noting that the `addObserver()` call was surrounded by `if (useNewLifecycleMethods) {` I tried adding 
```
    android: {
      experimentalUseNewLifecycleMethods: false,
```
to the call to `segment.setup()` in RN. This has no effect as `experimentalUseNewLifecycleMethods` is not passed through by [configuration.ts](https://github.com/segmentio/analytics-react-native/blob/master/packages/core/src/configuration.ts). Modifying the Java code to force this to true causes setup() to appear to complete successfully, though I've not verified if there are any other side-effects.

**Comment by danborthwick** [comment] 2021-03-29 05:54
If anyone needs a workaround, the combination of `react-native-purchases@3.4.3` and `@segment/analytics-react-native@1.3.2` appears to work and, in our case, was up to date enough for what we needed.

**Comment by gursesl** [comment] 2021-03-29 20:02
Similar issue #274

**Comment by josinaldobarbosa** [comment] 2021-03-30 18:04
I have the same problem with the following versions:
`segment/analytics-react-native:^1.4.1`
`react-native-purchases:^4.1.0`

I solved only changing:
`react-native-purchases:^3.4.3`

**Comment by adirkz** [comment] 2021-04-01 10:20
@danborthwick  did you find a solution?

**Comment by dotansimha** [comment] 2021-04-05 06:51
Same here. We do not use `react-native-purchases` at all, and it seems like this happens on in the built APK and not during development.

**Comment by tautvilas** [comment] 2021-04-07 08:24
I have same problem after updating Stripe dependency to 16.4.3

**Comment by PabloLerma** [comment] 2021-04-08 18:19
This is happening to us also, even without updating any relevant dependency

**Comment by Elter71** [comment] 2021-04-12 06:40
> This is happening to us also, even without updating any relevant dependency

Same

**Comment by NiklasMencke** [comment] 2021-04-13 08:50
same problem since updating react-native-purchases to
"react-native-purchases": "^4.1.1",

**Comment by alanjcharles** [comment] 2021-04-13 17:06
Closing since this is related to the `react-native-purchases` package which is not used by the `analytics-react-native` library in any way. I would recommend reaching out to the author of that package for further support. Please let me know if there is any additional evidence you would like me to consider to reopen this.

**Comment by dotansimha** [comment] 2021-04-13 17:11
If that helps anyone, in our case, we moved from the native Android appsflyer library to Segment, and we kept the piece of code in `MainActivity.java` that does `new Analytics.Builder`. This was the cause for this error.

**Comment by nfcampos** [comment] 2021-04-13 17:18
Hi guys,

This issue should not be closed. We are facing this in our app as well. `react-native-purchases` and `analytics-react-native` share a native android dependency. That dependency is `androidx.lifecycle:lifecycle-process`. 

By updating react-native-purchases that shared dependency is updated to 2.3.0, which then makes segment analytics crash, as it is segment which appears to be incompatible with this newer version of this shared dependency. 

Please see the release notes for this shared dependency which I'm sure will help you figure out what to fix on your side
https://developer.android.com/jetpack/androidx/releases/lifecycle#version_230_3

Thanks

**Comment by nobbyclark** [comment] 2021-04-14 00:09
I'm also seeing this issue and I'm not using `react-native-purchases`

**Comment by neerajbuccam** [comment] 2021-04-14 05:31
those facing issues please try this workaround below and see if it helps. This fix is related to a different issue though but it can help as both these issues are logged during same time.
https://github.com/segmentio/analytics-react-native/issues/289#issuecomment-818736118

**Comment by PabloLerma** [comment] 2021-04-14 11:10
Hey @alanjcharles ! We are facing this issue without using `react-native-purchase`. We fixed it downgrading `analytics-react-native` from 1.4.1 to 1.3.0 but of course this is not a long-term solution. How can we help?

**Comment by nobbyclark** [comment] 2021-04-14 19:35
@PabloLerma reverting to `1.3.0` solved the issue for me thanks.

**Comment by alanjcharles** [comment] 2021-04-15 17:10
Hi everyone, 

Thanks for all of the feedback!  I have been able to reproduce and we are looking into it. I hope to have more information for you by the end of the day or first thing tomorrow. Reopening for now.

**Comment by alanjcharles** [comment] 2021-04-16 18:46
Hi Everyone, 

We have pushed a fix for this here https://github.com/segmentio/analytics-react-native/pull/298

It seems Facebook introduced a [breaking change for Kotlin](https://github.com/facebook/react-native/commit/d76556543f96f4d739be3a708b8f6314bb32cc87) in `react-native 0.64` so we are testing to make sure the changes work with older versions in  an attempt to maintain our minimum version support at `react-native 0.62`. Hope to push a new release today or Monday.

**Comment by dotansimha** [comment] 2021-04-18 11:26
> Hi Everyone,
> 
> We have pushed a fix for this here #298
> 
> It seems Facebook introduced a [breaking change for Kotlin](https://github.com/facebook/react-native/commit/d76556543f96f4d739be3a708b8f6314bb32cc87) in `react-native 0.64` so we are testing to make sure the changes work with older versions in an attempt to maintain our minimum version support at `react-native 0.62`. Hope to push a new release today or Monday.

Worth mentioning that we are using `0.63.4` and having this issue on Android. Only in release APK, it doesn't happen during development.

**Comment by dotansimha** [comment] 2021-04-18 15:02
After digging into that, seems like no change at our end was the cause for this, and it's only something specific with this package and its dependencies. 

I can confirm that @prayansh / @alanjcharles fixes in https://github.com/segmentio/analytics-react-native/pull/298 really worked by changing `build.gradle` using `patch-package`.

Here is the `patch-package` diff that solved my problem:

```diff
diff --git a/node_modules/@segment/analytics-react-native/android/build.gradle b/node_modules/@segment/analytics-react-native/android/build.gradle
index a1b26ba..ac18943 100644
--- a/node_modules/@segment/analytics-react-native/android/build.gradle
+++ b/node_modules/@segment/analytics-react-native/android/build.gradle
@@ -39,7 +39,7 @@ repositories {
 }
 
 dependencies {
-    api 'com.segment.analytics.android:analytics:4.9.1-beta'
+    api 'com.segment.analytics.android:analytics:4.9.3'
 
     api 'com.facebook.react:react-native:+'
     api "org.jetbrains.kotlin:kotlin-stdlib:${rootProject.ext.has("kotlinVersion") ? rootProject.ext.get("kotlinVersion") : defaultKotlinVersion}"
diff --git a/node_modules/@segment/analytics-react-native/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt b/node_modules/@segment/analytics-react-native/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt
index 867a15b..1e01acd 100644
--- a/node_modules/@segment/analytics-react-native/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt
+++ b/node_modules/@segment/analytics-react-native/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt
@@ -106,6 +106,10 @@ class RNAnalyticsModule(context: ReactApplicationContext): ReactContextBaseJavaM
         val json = options.getString("json")
         val writeKey = options.getString("writeKey")
 
+        if (writeKey == null) {
+            return promise.reject("E_SEGMENT_RECONFIGURED", "writeKey cannot be null")
+        }
+
         if(singletonJsonConfig != null) {
             if(json == singletonJsonConfig) {
                 return promise.resolve(null)
@@ -183,6 +187,8 @@ class RNAnalyticsModule(context: ReactApplicationContext): ReactContextBaseJavaM
             })
         }
 
+        builder.experimentalUseNewLifecycleMethods(false)
+
         try {
             Analytics.setSingletonInstance(
                     RNAnalytics.buildWithIntegrations(builder)
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

@prayansh / @alanjcharles PLEASE CUT A RELEASE, this seems like a major issue that affects tons of applications, and it seems like something that isn't possible to catch in ci, during development, or even in release mode on some devices, so developers might notice that only when it's too late.

**Comment by igormontella** [comment] 2021-04-20 15:29
> After digging into that, seems like no change at our end was the cause for this, and it's only something specific with this package and its dependencies.
> 
> I can confirm that @prayansh / @alanjcharles fixes in #298 really worked by changing `build.gradle` using `patch-package`.
> 
> Here is the `patch-package` diff that solved my problem (I guess the version bump was the actual solution here):
> 
> ```diff
> diff --git a/node_modules/@segment/analytics-react-native/android/build.gradle b/node_modules/@segment/analytics-react-native/android/build.gradle
> index a1b26ba..ac18943 100644
> --- a/node_modules/@segment/analytics-react-native/android/build.gradle
> +++ b/node_modules/@segment/analytics-react-native/android/build.gradle
> @@ -39,7 +39,7 @@ repositories {
>  }
>  
>  dependencies {
> -    api 'com.segment.analytics.android:analytics:4.9.1-beta'
> +    api 'com.segment.analytics.android:analytics:4.9.3'
>  
>      api 'com.facebook.react:react-native:+'
>      api "org.jetbrains.kotlin:kotlin-stdlib:${rootProject.ext.has("kotlinVersion") ? rootProject.ext.get("kotlinVersion") : defaultKotlinVersion}"
> diff --git a/node_modules/@segment/analytics-react-native/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt b/node_modules/@segment/analytics-react-native/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt
> index 867a15b..1e01acd 100644
> --- a/node_modules/@segment/analytics-react-native/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt
> +++ b/node_modules/@segment/analytics-react-native/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt
> @@ -106,6 +106,10 @@ class RNAnalyticsModule(context: ReactApplicationContext): ReactContextBaseJavaM
>          val json = options.getString("json")
>          val writeKey = options.getString("writeKey")
>  
> +        if (writeKey == null) {
> +            return promise.reject("E_SEGMENT_RECONFIGURED", "writeKey cannot be null")
> +        }
> +
>          if(singletonJsonConfig != null) {
>              if(json == singletonJsonConfig) {
>                  return promise.resolve(null)
> @@ -183,6 +187,8 @@ class RNAnalyticsModule(context: ReactApplicationContext): ReactContextBaseJavaM
>              })
>          }
>  
> +        builder.experimentalUseNewLifecycleMethods(false)
> +
>          try {
>              Analytics.setSingletonInstance(
>                      RNAnalytics.buildWithIntegrations(builder)
> ```
> 
> _This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296)._
> 
> @prayansh / @alanjcharles Please, please cut a release :) this seems like a major issue that might affect many applications, and it seems like something that isn't possible to catch in ci, reproduce during development, or even reproduce in release mode on some devices, so developers might notice that only when it's too late.

It worked for me!

**Comment by bernardn98** [comment] 2021-04-20 17:15
URGENT Please help cut a release for us for this fix, it is blocking us from creating a new build.  We tried to pull from a specific commit but it's not allowing us. 

Error: Can't add "@segment/analytics-react-native": invalid package version undefined.

What we tried in our package.json -->
"@segment/analytics-react-native": "https://github.com/segmentio/analytics-react-native.git#5a2ed9bb8b62b89c4ce557b76c7b98a91b309e27"

**Comment by alanjcharles** [comment] 2021-04-27 19:59
Hi- we pushed a the release this morning! Apologies for the delay. Please feel free to reopen if you're still running into issues and we can take a closer look.

**Closed by alanjcharles** 2021-04-27 19:59 UTC
