### ISSUE TITLE
Error: The package 'sovran-react-native' doesn't seem to be linked

### ISSUE THREAD

**Issue by clinton15** [segmentio/analytics-react-native#529] opened 2022-05-06 18:38 UTC
I'm using sovran-react-native version : 0.2.6
I tried the fixes mentioned in the previous tickets for this issue but they did not work for me. 
- `analytics-react-native` version: 2.1.12
- Integrations versions (if used):
- React Native version: 0.67.3
- iOS or Android or both? Android

**Steps to reproduce**
npm install --save @segment/analytics-react-native @segment/sovran-react-native @react-native-async-storage/async-storage

**Expected behavior**
Expected my app to build and load without crashing.

**Actual behavior**
App crashes with the below error:

```
 Error: The package 'sovran-react-native' doesn't seem to be linked. Make sure:

- You rebuilt the app after installing the package
- You are not using Expo managed workflow
- js engine: hermes
```

**Comment by alanjcharles** [comment] 2022-05-06 19:17
Hi @clinton15 I am unable to reproduce this, I'm afraid. Here is the `package.json` of a simple `hello world` app I spun up to test: 

```
{
  "name": "sovranBug",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.17.3",
    "@segment/analytics-react-native": "^2.1.12",
    "@segment/sovran-react-native": "^0.2.6",
    "react": "17.0.2",
    "react-native": "0.68.1"
  },
  "devDependencies": {
    "@babel/core": "^7.17.10",
    "@babel/runtime": "^7.17.9",
    "@react-native-community/eslint-config": "^3.0.1",
    "babel-jest": "^28.1.0",
    "eslint": "^8.14.0",
    "jest": "^28.1.0",
    "metro-react-native-babel-preset": "^0.70.3",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

App.js 
```
...

import {
  createClient,
  AnalyticsProvider,
} from '@segment/analytics-react-native';

const segmentClient = createClient({
  writeKey: 'WRITE_KEY',
  trackAppLifecycleEvents: true,
  collectDeviceId: true,
  debug: true,
  trackDeepLinks: true,
});

...

const App: () => Node = () => {
  const isDarkMode = useColorScheme() === 'dark';

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  return (
    <AnalyticsProvider client={segmentClient}>
        ...
       <App Components...>
      ....
    </AnalyticsProvider>
  );
};


```
Screenshot of the successful build 
![image](https://user-images.githubusercontent.com/50601149/167203359-1a8dee8f-fcba-4843-ac50-9a686e8e136e.png)


I would recommend clearing you caches/ resetting the build. Going to close this out for now, please feel free to reopen with more information or reach out to friends@segment.com for additional support

**Closed by alanjcharles** 2022-05-06 19:17 UTC
Labels: bug
