### ISSUE TITLE
An internal error occurred: Status code failure 404

### ISSUE THREAD

**Issue by ns-wahed** [segmentio/analytics-react-native#825] opened 2023-05-05 15:10 UTC
Hi Team,
We are trying to add a `@segment/analytics-react-native-plugin-appsflyer` as a plugin, and whenever we are using the `track` function `segmentClient` it throws an error of `Status code 404`, is anyone facing the same?

**Here's the code we are using to add the plugin:** 

```tsx
import {createClient, SegmentError} from '@segment/analytics-react-native';
import {AppsflyerPlugin} from '@segment/analytics-react-native-plugin-appsflyer';

const errorHandler = (error: SegmentError) => {
  console.info('ERROR ON SEGMENT CLIENT  ------  ', error);
};

const segmentClient = createClient({
  writeKey: SEGMENT_KEY,
  trackAppLifecycleEvents: true,
  autoAddSegmentDestination: true,
  errorHandler
});
const plugin = new AppsflyerPlugin();
segmentClient.add({plugin});
```

```
"@segment/analytics-react-native": "^2.14.0",
"@segment/analytics-react-native-plugin-appsflyer": "^0.5.2",
"@segment/sovran-react-native": "^1.0.2",
"react": "18.0.0",
"react-native": "0.69.8",
``` 

![Screenshot 2023-05-05 at 8 09 18 PM](https://user-images.githubusercontent.com/115992989/236496980-4fac5928-e3f5-406a-969c-34649e95061f.png)

**Comment by alanjcharles** [comment] 2023-05-17 20:51
Hi @ns-wahed I've been trying to track this down for a few weeks. I get this error when I use Appsflyer in our example and in a standalone `hello-world` app just using the Appsflyer SDK without Segment. The only place I could get it to work was with the actual AppsFlyer react native example in their repository. It seems to me they've changed something on their end and it's not apparent as to what that could be. I would recommend reaching out to them, or trying to just initialize the Appsflyer SDK outside of Segment to see if your experience is the same. Please let me know, at this point there's not much we can do on our side.

**Comment by alanjcharles** [comment] 2024-07-25 18:30
Hi folks, 

Closing this as I have been unable to reproduce it on the latest versions of `react-native-appsflyer`. If you are still experiencing issues please reach out to `friends@segment.com` for assistance from our support engineering team who can escalate any issues accordingly. Thanks!

**Closed by alanjcharles** 2024-07-25 18:30 UTC
Labels: bug
