### ISSUE TITLE
Android not syncing modules

### ISSUE THREAD

**Issue by amitassaraf** [segmentio/analytics-react-native#14] opened 2018-10-30 18:44 UTC
When trying to sync the android project after linking the modules needed I receive the following message:

Caused by: org.gradle.api.UnknownProjectException: Project with path ':@segment_analytics-react-native' could not be found in project ':@segment/analytics-react-native-google-analytics'.

I couldn't find a solution for this..

**Comment by amitassaraf** [comment] 2018-10-30 19:20
I fixed this by changing the @segment/analytics-react-native-google-analytics and @segment/analytics-react-native-mixpanel build files to include the project by relative path.

This:
`compileOnly project(":@segment_analytics-react-native")`

Changed to this:
`compileOnly files("../../analytics-react-native/android")`

But now when I try running the project I get a lot of unresolved references in the mixpanel project.

` Unresolved reference: facebook`
` Unresolved reference: core`
` Unresolved reference: ReactApplicationContext`
`...`

**Comment by amitassaraf** [comment] 2018-10-30 20:06
I was able to reduce the unresolved references into two unresolved references by adding the following into the project dependencies for both the google analytics and mixpanel projects:

`api 'com.facebook.react:react-native:+'
    api 'org.jetbrains.kotlin:kotlin-stdlib:1.2.+'
    api 'com.segment.analytics.android:analytics:4.+'`

This reduced the problem into two unresolved references:
`Unresolved reference: core`
`Unresolved reference: RNAnalytics`

**Comment by amitassaraf** [comment] 2018-10-30 20:34
I solved this by manually configuring the projects in each device support extension i added manually. I believe this happened due to the fact that you use `@` in the module name and it caused issues importing the gradle modules.

**Comment by fathyb** [comment] 2018-11-02 23:36
Hey @amitassaraf, thanks for the report! It looks like a linking issue: when you install our library isn't linked to your native projects yet (Podfile or Gradle). You have to run `react-native link` to ask React to traverse your native libraries and link them to your native projects. Sometimes (ie. your project is too syntactically complicated) React Native cannot link your libraries, usually (but not always) it's followed by an error message when running `react-native link`.

In short:
- Unfortunately, we don't control how `react-native` parses your native project. [We test our library on a brand new react-native project generated from scratch](https://circleci.com/gh/segmentio/analytics-react-native/797) to be sure we're always working with the latest React-Native projects.
- This should also affect other native libraries, something like [react-native-signature-capture](https://github.com/RepairShopr/react-native-signature-capture) should also exhibit the same behavior.
- We recommend you to report this issue to [react-native GitHub repository](https://github.com/facebook/react-native) with a minimal reproduction. If you have the minimal reproduction we'd also be interested to take a look at it.

I'm closing this as it looks like you've resolved it. Feel free to reopen this issue if you have any questions!

**Closed by fathyb** 2018-11-02 23:36 UTC
