### ISSUE TITLE
The package 'sovran-react-native' doesn't seem to be linked. Expo managed workflow

### ISSUE THREAD

**Issue by danielgangverk** [segmentio/analytics-react-native#661] opened 2022-09-06 17:33 UTC
I'm running Expo managed workflow and running the app in Expo go which I know is not compatible with the package but I think I should still be able to run the app even though the analytics package is not going to work. Expected behaviour would be a warning and the package not working (like happens in the Sentry package f.ex.).

  `"expo": "^46.0.10",`
- `analytics-react-native` version:     
  "@segment/analytics-react-native": "^2.7.1",
   "@segment/sovran-react-native": "^0.4.4",
   "@react-native-async-storage/async-storage": "^1.17.10",
- Integrations versions (if used):
- React Native version:     "react-native": "0.69.5"
- iOS or Android or both? iOS

**Steps to reproduce**

- Create expo project (`npx create-expo-app my-app`)
- Run `yarn add @segment/analytics-react-native @segment/sovran-react-native @react-native-async-storage/async-storage`
- Add the following to your App.tsx so that the package gets used:
```javascript
import { AnalyticsProvider, createClient } from '@segment/analytics-react-native';

const segmentClient = createClient({});
```

Snack https://snack.expo.dev/@danielgangverk/segment-snack?platform=ios

**Expected behavior**
I would expect a warning that the package doesn't work with Expo go instead of a crash

**Actual behavior**
The app crashes in Expo go if @segment/analytics-react-native is imported anywhere

**Comment by Jorundur** [comment] 2022-09-07 12:49
Same issue here, using Expo 44

**Comment by Jorundur** [comment] 2022-09-07 13:52
I see now that the ReadMe says

> ⚠️ @segment/analytics-react-native 2.0 is not compatible with Expo Go.

But I agree with @danielgangverk  - it would be better if it was just completely disabled somehow when running in Expo Go and a warning displayed perhaps, instead of it blowing up.

Expo deprecated `expo-analytics-segment` in favor of this library from Expo 46 onwards, and it would be good to be able to continue using Expo Go after switching over to `@segment/analytics-react-native`

**Comment by oscb** [comment] 2022-09-07 20:29
Putting this as an enhancement. I'm not familiar with Expo but I'm pretty sure we will need to check if the NativeModule exists and catch those exceptions in those scenarios.

**Comment by nickwelp** [comment] 2022-09-07 22:00
you can follow a work around here, https://github.com/segmentio/sovran-react-native/issues/39#issuecomment-1223897361 That was able to get my Expo 46 app building with Segmentio

**Comment by danielgangverk** [comment] 2022-09-08 12:54
@nickwelp Thanks for the suggestion. 
Unfortunately, my issue is with running the app on the **Expo go** client on **iOS**. The issue you mentioned is about **building** the app for **Android**.

Building works just fine for me, it's just that running the Expo go client when I have this library installed causes an app crash.

**Comment by gislitg** [comment] 2022-09-09 18:12
I have the same issue with ExpoGo and @segment/sovran-react-native, it crashes when running inside ExpoGo, I think a warning would be nice,  it really doesn't leave ExpoGo users with a lot of choices regarding Segment integration. I think it actually crashes right at the import and not even its usage.

**Comment by gislitg** [comment] 2022-09-12 10:45
@danielgangverk @Jorundur A workaround for this (on iOS at least, have not tested Android yet) can be implemented by only requiring the module when we have the NativeModule, so it will work for any EAS build, with or without dev-client. For ExpoGo you could then just __DEV__ log your Segment calls or skip them, that should keep ExpoGo usable at least.

```
    const { AnalyticsReactNative } = NativeModules;
    if (client || !AnalyticsReactNative) {
      return;
    }

    const segmentAnalytics = require('@segment/analytics-react-native');
    client = segmentAnalytics.createClient({
      writeKey,
    });`
```

**Comment by konoufo** [comment] 2022-10-03 22:49
@danielgangverk We have merged changes in both this library and sovran-react-native that should fix the issue. You can now use Expo Go without crashing. All you'll get is a friendly warning. These changes should also be released soon. In the meantime, pulling from master should do the trick.

**Closed** 2022-10-07 10:58 UTC
Labels: enhancement

**Comment by amerikan** [comment] 2022-10-07 22:43
@konoufo do you know what version will this be fixed on? I notice 2.9.0 was just published and I tried that, but still crashing on my expo go. Not sure if the new version includes the fix.

**Comment by konoufo** [comment] 2022-10-10 20:16
> @konoufo do you know what version will this be fixed on? I notice 2.9.0 was just published and I tried that, but still crashing on my expo go. Not sure if the new version includes the fix.
> 
> UPDATE: nvm seems like sovran-react-native hasn't been released yet. I will try when a new version is out.

Yeah that's right; it's going live with the next `sovran-react-native` release.

**Comment by jakescript** [comment] 2022-10-14 17:43
@konoufo wondering if while this is being fixed is it possible to use segmentio/analytics-next? what exactly does the react native library do that next doesn't?

**Comment by webjay** [comment] 2022-10-24 07:48
@konoufo any idea when there will be a new release of `sovran-react-native`?

**Comment by webjay** [comment] 2022-10-26 17:27
It works now, and I can see Application Opened events in Segment.

I see this:

> The package 'analytics-react-native' can't access a custom native module. Make sure: 
> 
> - You have run 'pod install'
> - You rebuilt the app after installing the package
> - You are not using Expo managed workflow

- expo: 46.0.16
- @segment/analytics-react-native: 2.9.0
- @segment/sovran-react-native: 0.4.5

**Comment by konoufo** [comment] 2022-10-26 18:05
Hey @webjay . Do you see this as a warning ? If so, then yeah sounds like it's working exactly as intended! Thanks for your feedback!

**Comment by konoufo** [comment] 2022-10-26 18:07
@jakescript I don't know much about segmentio/analytics-next. But analytics-react-native 2.0 is the recommended way for RN apps. It's only going to get better from here.

**Comment by rjzheng** [comment] 2022-10-29 04:49
Hey guys, any insights on why I'm still getting this after I upgraded? I'm using the same exact versions as @webjay.
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/6020627/198814480-9ebdf8a6-fee8-4c56-b31b-60cca87805fd.png">

**Comment by amerikan** [comment] 2022-10-30 00:39
@konoufo seems to be good now that I also updated sovran. 

As a side question, do you happen to know how can I make this package work with **react native web** (or at least not crash in it)? Prior to using this I was using **expo-segment** (but they're removing it in [Expo SDK 46](https://blog.expo.dev/expo-sdk-46-c2a1655f63f7)), hence now having to use this. expo-segment allowed me to use segment for **react native web** without crashing. Now, when I use this @segment/analytics-react-native and @segment/sovran-react-native instead of expo-segment for react native **web** build it crashes. I will investigate a solution, but was wondering if you had some guidance.

**Comment by bk3** [comment] 2022-12-14 06:46
> segmentio/sovran-react-native#39 (comment)

I setup two different analytics utilities using `react-segments` for the web and `@segment/analytics-react-native` for native

**Comment by bk3** [comment] 2022-12-14 06:47
> @konoufo seems to be good now that I also updated sovran.
> 
> As a side question, do you happen to know how can I make this package work with **react native web** (or at least not crash in it)? Prior to using this I was using **expo-segment** (but they're removing it in [Expo SDK 46](https://blog.expo.dev/expo-sdk-46-c2a1655f63f7)), hence now having to use this. expo-segment allowed me to use segment for **react native web** without crashing. Now, when I use this @segment/analytics-react-native and @segment/sovran-react-native instead of expo-segment for react native **web** build it crashes. I will investigate a solution, but was wondering if you had some guidance.

I setup two different analytics utilities using react-segments for the web and @segment/analytics-react-native for native
