### ISSUE TITLE
Use of undeclared identifier 'AnalyticsReactNative' on Xcode 14

### ISSUE THREAD

**Issue by quanKM** [segmentio/analytics-react-native#698] opened 2022-10-26 03:13 UTC
After updating to Xcode 14, I get this error when building my application on iOS Simulator. When I build on a real device,  things still work perfectly fine.

<img width="971" alt="Screenshot 2022-10-26 at 10 07 31" src="https://user-images.githubusercontent.com/38641481/197925228-ce865352-6c28-4585-bce0-2b5842ef93f1.png">

<img width="1270" alt="Screenshot 2022-10-26 at 10 30 35" src="https://user-images.githubusercontent.com/38641481/197928066-4f3aa487-2544-476f-bbd0-fc5d72a0459c.png">

- `analytics-react-native` version: 2.9.0
- React Native version: 0.67.4

**Steps to reproduce**
- Update to Xcode 14
- Build application on an emulator
**Expected behavior**
- Cannot run the application on iOS Simulator
**Actual behavior**
- Can run the application on iOS Simulator

**Comment by oscb** [comment] 2022-11-01 15:47
Taking a look at this.

**Comment by quanKM** [comment] 2022-11-03 17:29
I think this can be related to "react-native-vision-camera". With Xcode 14, I also update these
`"react-native-vision-camera": "2.14.1",
"vision-camera-code-scanner": "^0.2.0",
"react-native-reanimated": "2.10.0",
` when this error starts to occur. Maybe this can lead to some ideas.

**Comment by alanjcharles** [comment] 2022-11-07 16:56
Hi @quanKM I am able to build as expected with the following versions: 

`React Native`: 0.69.2
`analytics-react-native`: 2.9.1
`Xcode`:  14.1 

I would recommend updating your version of `React Native` as it seems there have been some pretty big changes in newer versions to account for Xcode 14 and iOS 16. Since we can't reproduce, I'm going to close this out for now. Please feel free to respond with more information if you're still running into issues.

**Closed by alanjcharles** 2022-11-07 16:56 UTC
Labels: bug, 🚧 Work In Progress

**Comment by nreavesHRC** [comment] 2023-01-20 18:55
Hey @quanKM, Did you resolve this error? We are encountering the same issue and also upgrading vision camera as well during our upgrade to RN 0.70.x

**Comment by quanKM** [comment] 2023-02-22 06:58
> 

Sadly, not having any solution yet.
