### ISSUE TITLE
Initial Lifecycle events miss context information

### ISSUE THREAD

**Issue by BerniWittmann** [segmentio/analytics-react-native#527] opened 2022-05-05 06:44 UTC
Aswe want to setup ads tracking with google ads we need to have some device context data set on the initial lifecycle events (especially Application Installed and Application Opened). However this information is missing most of the time (from my observations not all of the time, but most of them). I have found https://github.com/segmentio/analytics-react-native/issues/449 which describes the same issue with a beta version, but I am on the latest version and it still happens for me.

- `analytics-react-native` version: 2.1.12
- Integrations versions (if used): idfa: 0.2.1
- React Native version: 0.63.3
- iOS or Android or both?: both

**Steps to reproduce**

have ` trackAppLifecycleEvents: true,` activated in the client and reinstall and open app, while checking the debugger on segment.com

**Expected behavior**

```
{
  "anonymousId": "xxxx",
  "context": {
    "app": {
      "build": "0",
      "name": "App",
      "namespace": "app.name",
      "version": "1.0.0"
    },
    "device": {
      "adTrackingEnabled": false,
      "advertisingId": "xxxx",
      "trackingStatus": "notDetermined",
      "id": "xxxx",
      "manufacturer": "Apple",
      "model": "x86_64",
      "name": "i***",
      "type": "ios"
    },
    "library": {
      "name": "@segment/analytics-react-native",
      "version": "2.1.12"
    },
    "os": {
      "version": "15.4"
    }
  },
  "event": "Application Opened",
  "integrations": {},
  "messageId": "xxx",
  "originalTimestamp": "2022-05-05T06:39:41.995Z",
  "properties": {
    "build": "0",
    "from_background": false,
    "version": "1.61.0"
  },
  "receivedAt": "2022-05-05T06:40:12.978Z",
  "sentAt": "2022-05-05T06:40:11.990Z",
  "timestamp": "2022-05-05T06:39:42.983Z",
  "type": "track",
  "writeKey": "xxxxx"
}
```

**Actual behavior**

```
{
  "anonymousId": "xxxx",
  "context": {
    "app": {
      "namespace": "app.name",
      "version": "1.0.0"
    },
    "device": {
      "adTrackingEnabled": false,
      "advertisingId": "xxxx",
      "trackingStatus": "notDetermined"
    },
    "library": {
      "name": "unknown",
      "version": "unknown"
    },
    "os": {
      "version": "15.4"
    }
  },
  "event": "Application Opened",
  "integrations": {},
  "messageId": "xxx",
  "originalTimestamp": "2022-05-05T06:39:41.995Z",
  "properties": {
    "build": "0",
    "from_background": false,
    "version": "1.61.0"
  },
  "receivedAt": "2022-05-05T06:40:12.978Z",
  "sentAt": "2022-05-05T06:40:11.990Z",
  "timestamp": "2022-05-05T06:39:42.983Z",
  "type": "track",
  "writeKey": "xxxxx"
}
```

**Comment by oscb** [comment] 2022-05-05 18:10
@BerniWittmann Thanks for the report. I'm trying to repro this issue right now. Is this happening on the simulators or on device for you?

**Comment by BerniWittmann** [comment] 2022-05-05 18:49
@oscb Thanks for the quick response time. I can see it happen from simulators as well as running on a device

**Comment by oscb** [comment] 2022-05-06 04:06
@BerniWittmann I haven't got a clear repro yet, but I have a strong idea of what might be causing this. I'm going to aim to get a fix for this soon, if all looks good it should be out by tomorrow

**Comment by oscb** [comment] 2022-05-10 01:05
The change in PR #532 should address this. 

I wasn't able to repro but I believe this was caused by a concurrency issue as the store updates were not awaitable before, the change guarantees the `Application Opened/Installed` events are always triggered after the context is actually available in the store.

**Closed** 2022-05-10 15:38 UTC
Labels: bug, 🚧 Work In Progress

**Comment by BerniWittmann** [comment] 2022-05-15 10:40
@oscb Thank you very much for the quick turnaround. Just gave it a quick test and it looks good :+1:

**Comment by i8ramin** [comment] 2022-05-19 17:00
Does the latest published version on npm (`2.2.0`) include this change? https://www.npmjs.com/package/@segment/analytics-react-native

**Comment by i8ramin** [comment] 2022-05-19 17:03
Also, i don't even see `v2.2.0` as a tag in the repo. latest tagged version seems to be `v2.1.12`

**Comment by oscb** [comment] 2022-05-19 17:10
@i8ramin v2.2.0 contains this change. 
GHA created an incorrect tag, but it shows up in the [releases](https://github.com/segmentio/analytics-react-native/releases/tag/refs%2Fheads%2Fmaster).

**Comment by i8ramin** [comment] 2022-05-23 15:37
I am still experiencing inconsistent behavior here. Sometimes the device context information is there, sometimes it is not. I am observing this behavior with latest version (`2.2.0`) -- where the `context.device` does not include actual device information. Sample output:

```json
    "device": {
      "adTrackingEnabled": true,
      "advertisingId": "CF8EAEA5-0000-481D-0000-25140DB49B96",
      "trackingStatus": "authorized"
    },
```

This is how I am setting up the library + plugins

```ts
import { createClient } from '@segment/analytics-react-native'
import { FacebookAppEventsPlugin } from '@segment/analytics-react-native-plugin-facebook-app-events'
import { FirebasePlugin } from '@segment/analytics-react-native-plugin-firebase'
import { IdfaPlugin } from '@segment/analytics-react-native-plugin-idfa'

const segmentClient = createClient({
  writeKey: process.env.ANALYTICS_WRITE_KEY as string,
  trackAppLifecycleEvents: true,
  trackDeepLinks: true,
  collectDeviceId: true,
  debug: true,
})

segmentClient.add({ plugin: new IdfaPlugin() })
segmentClient.add({ plugin: new FacebookAppEventsPlugin() })
segmentClient.add({ plugin: new FirebasePlugin() })

export default segmentClient
```

```
analytics-react-native version: 2.2.0
Integrations versions (if used): idfa: 0.2.1
React Native version: 0.64.3
iOS or Android or both?: ios
```
