### ISSUE TITLE
Project with path ':@segment_analytics-react-native' could not be found in project

### ISSUE THREAD

**Issue by juliandondero** [segmentio/analytics-react-native#21] opened 2018-11-21 16:57 UTC
FAILURE: Build failed with an exception.

* Where:
Build file '.../node_modules/@segment/analytics-react-native-google-analytics/android/build.gradle' line: 43

* What went wrong:
A problem occurred evaluating project ':@segment/analytics-react-native-google-analytics'.
> Project with path ':@segment_analytics-react-native' could not be found in project ':@segment/analytics-react-native-google-analytics'.

**Comment by juliandondero** [comment] 2018-11-28 12:38
i made a pr with the fix ( https://github.com/segmentio/analytics-react-native/pull/22 ) , but nobody reply... if i change build.gradle of integration project, i can build... but i don't want fork the project for this!

**Comment by fathyb** [comment] 2018-12-05 16:09
We're already testing that Android generated integrations are building correctly. What Gradle version are you using?

**Comment by danalloway** [comment] 2018-12-17 16:17
@juliandondero what version of Android Studio are you using?

**Comment by juliandondero** [comment] 2018-12-19 12:41
i'm using gradle 4.4 and building with react-native scripts, when i build the project, i get:

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/Julian/workspace/go5-gobenefits-mobile/node_modules/@segment/analytics-react-native-google-analytics/android/build.gradle' line: 43

* What went wrong:
A problem occurred evaluating project ':@segment/analytics-react-native-google-analytics'.
> Project with path ':@segment_analytics-react-native' could not be found in project ':@segment/analytics-react-native-google-analytics'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
if i change _ for / in the module build.gradle the project build

**Comment by danalloway** [comment] 2018-12-19 14:08
@juliandondero we encountered a similar issue but only on Android Studio 3.1 (which is the version recommended by react-native as of the 0.57 release) was curious if that is the version of studio that you're on?

**Comment by juliandondero** [comment] 2018-12-19 14:11
thanks! i'm using android studio 3.1.2, what can i do? i can't build the project with this dependencies.

**Comment by danalloway** [comment] 2018-12-19 14:36
we are not using the google analytics integration so I can't speak to that, but for our vanilla install we changed how we import this project in our `app/build.gradle` and `settings.gradle` files

settings.gradle
```
include ':@segment_analytics-react-native'
project(':@segment_analytics-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/@segment/analytics-react-native/android')
```

build.gradle
```
implementation project(':@segment_analytics-react-native')
```

**Comment by danalloway** [comment] 2018-12-19 14:41
for whatever reason the earlier version of Android Studio (3.1.x) changes the module name to an underscore internally when it loads it, so any reference to a project like `@segment/***` must be changed to reflect that

I'm assuming the project authors are using a 3.2.x build of studio which is why everything works for them, but 3.1.x is still the recommended version of studio to use with react-native per https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#tooling-updates

**Comment by f2prateek** [comment] 2018-12-19 17:06
I am not so sure it's due to the version of Android Studio directly, as we don't use Android Studio on CI.  It's more likely to be some other dependency. See 
https://github.com/segmentio/analytics-react-native/pull/22#pullrequestreview-181823813.

**Comment by danalloway** [comment] 2018-12-19 17:31
that makes sense, so it's a gradle 4.4 issue then

**Comment by jacob-israel-turner** [comment] 2019-04-09 17:08
We're still having this issue with a fresh install of Segment.  On Android Studio version 3.2.1 and Gradle version 4.6.

**Comment by maour** [comment] 2019-05-10 06:33
I also had this `Could not resolve project :@segment_analytics-react-native` problem,
It is usually related to build types we use other than release and debug.

Try adding this line to your custom build

buildTypes {
        customapp {
            **matchingFallbacks = ['release']**
        }

**Comment by jacob-israel-turner** [comment] 2019-05-10 19:54
> I also had this `Could not resolve project :@segment_analytics-react-native` problem,
> It is usually related to build types we use other than release and debug.
> 
> Try adding this line to your custom build
> 
> buildTypes {
> customapp {
> **matchingFallbacks = ['release']**
> }

We resolved this issue a while ago.  We actually already had the `matchingFallbacks` line in our `build.gradle` - the issue is that we had `matchingFallbacks = ['release', 'debug']`.  After deleting `'debug'`, the issue was resolved.  Definitely weird, but we didn't actually need to fallback to `'debug'`, so the solution works for us.

**Comment by theonetheycallneo** [comment] 2019-05-10 20:24
I was able to solve this by changing the path to ```api project(":analytics-react-native")``` to support the new `yarn add @segment/react-native`

https://github.com/FreebirdRides/segment-analytics-react-native-appsflyer/commit/6dbccc4ca7f1899ab5f2cd710ce01489210466ae

**Comment by akshaymanathkar** [comment] 2019-10-03 16:02
is there a solution for this yet or not. I am seeing this issue as well

**Comment by rborn** [comment] 2020-02-17 14:14
I had to make a mix between this and 

`exclude("META-INF/*.kotlin_module") ` in `packagingOptions`

and it started compiling again 😒

**Comment by bsgbryan** [comment] 2020-02-27 19:00
I am having this issue as well. For me, changing line 41 to `api project(":segment_analytics-react-native")` _(removing the @)_ stopped the error from occurring.

**Comment by ardyfeb** [comment] 2020-03-16 16:42
Even 2 years this issue not fvcking resolve

**Comment by bsneed** [comment] 2020-03-16 16:53
We'll look at this for our next library release, should be soon.

**Comment by bsneed** [comment] 2020-03-16 16:54
A PR once a solution is found wouldn't certainly expedite things.

**Comment by lordkiz** [comment] 2020-03-18 09:29
> I am having this issue as well. For me, changing line 41 to `api project(":segment_analytics-react-native")` _(removing the @)_ stopped the error from occurring.

Thanks @bsgbryan . Also remember to use [patch-package](https://www.npmjs.com/package/patch-package)

**Comment by bsgbryan** [comment] 2020-03-18 16:58
Absolutely, glad to help!

And good call - that's exactly what we've done. We created a patch and use patch-package to apply that patch as part of the postinstall step.

**Comment by bsneed** [comment] 2020-03-19 21:49
We believe this to be resolved via PR #147, please reopen if that is not the case.

**Closed by bsneed** 2020-03-19 21:49 UTC
Labels: bug

**Comment by jeiemgi** [comment] 2020-03-24 21:57
Hi, @bsneed  , which version of the library should we use?  I keep getting that error.
```bash
FAILURE: Build failed with an exception.

* Where:
Build file '...node_modules/@segment/analytics-react-native-mixpanel/android/build.gradle' line: 41

* What went wrong:
A problem occurred evaluating project ':segment_analytics-react-native-mixpanel'.
> Project with path ':@segment_analytics-react-native' could not be found in project ':segment_analytics-react-native-mixpanel'.
```

I currently have these versions, I've tried many of them:

- @segment/analytics-react-native": "1.1.0-beta.2
- @segment/analytics-react-native-mixpanel": "^1.1.0-beta.2

**Comment by bsneed** [comment] 2020-03-24 22:50
Hi @jeiemgi,

I'm not a react-native expert by any means, mostly native iOS/android, so I'd say if you were using manual linking before and it was working, probably best to stick with it.  Our current beta version is actually 1.1.1-beta.0, and the last GM release was 1.1.0.  Also, I've yet to test with any RN versions beyond 0.59 too, so there may be issues lurking there.

**Comment by jeiemgi** [comment] 2020-03-24 23:11
@bsneed Thanks, 1.1.0 with manual linking works, I think the problem is autolinking

**Comment by warrify** [comment] 2020-04-20 00:09
Hi I had the same problem. I had to do:
```diff
-    api project(":@segment_analytics-react-native")
+    api project(":segment_analytics-react-native")
```

**Comment by bsgbryan** [comment] 2020-05-29 17:43
This should be reopened as this issue has been reintroduced.

On my project, we had to reapply the fix I mentioned previously; including reinstalling and reconfiguring `patch-package`.

**Comment by bsneed** [comment] 2020-05-29 17:57
@bsgbryan what version of react-native are you using?

**Comment by jfrolich** [comment] 2020-07-29 03:29
> Hi I had the same problem. I had to do:
> 
> ```diff
> -    api project(":@segment_analytics-react-native")
> +    api project(":segment_analytics-react-native")
> ```

In the newest version `1.2.1` you need to `patch-package` the reverse to make it all work 🙈

**Comment by bsgbryan** [comment] 2020-08-07 16:02
Yeah. At some point they fixed this. It appears it has returned as a regression.

**Comment by sampsonjoliver** [comment] 2020-11-12 00:14
Yep, confirmed on RN <0.62. I used the solution at https://github.com/segmentio/analytics-react-native/issues/164#issuecomment-617491564 but applied it in reverse, so going from

```
api project(":segment_analytics-react-native")
```
to
```
api project(":@segment_analytics-react-native")
```

This was necessary for us to do, in order to upgrade our RN Firebase from v5 to latest, which was a blocking step towards next being able to upgrade to RN 0.62+.
