### ISSUE TITLE
Events fired before app is killed never send – even after re-opening

### ISSUE THREAD

**Issue by ary31415** [segmentio/analytics-react-native#833] opened 2023-05-18 23:38 UTC
- `analytics-react-native` version: ^2.13.4
- Integrations versions (if used):
- React Native version: 0.71.7
- iOS or Android or both? iOS

**Steps to reproduce**
Open app, fire some arbitrary analytics events, then kill app before `flushAt` or `flushInterval` for segment client is reached. Reopen app.

**Expected behavior**
Backlogged analytics events should be persisted and sent to server as soon as app is reopened – or failing that, along with the next batch of events generated in the new session.

**Actual behavior**
Events from the new session are created and sent as expected, events from the first session are simply lost.

**Comment by jinsung-kim** [comment] 2023-05-19 20:36
+1

**Comment by oscb** [comment] 2023-05-22 23:34
It is possible this was caused by [this import issue](https://github.com/segmentio/analytics-react-native/pull/820) that got fixed in Sovran 1.0.3.

Can you upgrade sovran? Make sure to install also `@react-native-async-storage/async-storage` or use your own persistor.

**Comment by ary31415** [comment] 2023-06-01 19:19
I updated Sovran and this mostly alleviated the issue.

When I kill the app and then reopen it, events are not sent immediately, seeming to be in slight conflict with the README? The doc says "By default, the analytics will be sent ... whenever the app resumes if the user has closed the app with some events unsent.", which is the behavior I observe when I put the app in background and then later resume it – the backlogged events are sent immediately. By contrast, when I kill it and re-open it, there is no immediate batch of events sent.

However, when I do receive a batch of events once the `flushInterval` is reached, the events from the previous app session are included among them, which is good.

**Comment by viraj-nikam** [comment] 2023-06-14 16:34
We are also facing the same issue and even after updating to Sovran 1.0.4, it doesn't seem to alleviate the issue at all. All the events before app kill are lost completely.

**Comment by liamfd-titan** [comment] 2023-09-19 20:13
Just wanted to see if there are any updates on this one, we think it may be related to see data issues we've seen since upgrading from 1.x to 2.15.0.

**Comment by ddemid** [comment] 2023-10-05 13:57
Same issue here - 2.16.0

**Comment by dane-thomas-vs** [comment] 2023-12-04 15:11
Hello, bumping this issue as we are also experiencing this in our application. Manually flushing the event cache after critical events were fired helped alleviate, but I'm hoping for a less manual solution.

**Comment by alanjcharles** [comment] 2024-07-30 14:34
Hi folks- it is my understanding that this was resolved in this PR #916  please let me know if that is not the case or if you are still experiencing any issues and we can go from there. Thanks!

**Closed by alanjcharles** 2024-07-30 14:34 UTC
Labels: bug
