### ISSUE TITLE
MixpanelReactNative.initialize was called with 3 arguments but expects 5 arguments.

### ISSUE THREAD

**Issue by simonmasinde** [segmentio/analytics-react-native#701] opened 2022-11-02 10:50 UTC
- `analytics-react-native` version: 2.9.1
- Integrations versions (if used):
         @segment/analytics-react-native-plugin-mixpanel
- React Native version: 0.70.2
- iOS or Android or both?
both
**Steps to reproduce**

**Expected behavior**

**Actual behavior**

**Comment by sonnguyprophet** [comment] 2022-11-03 02:21
@simonmasinde we have faced the same issue, which we fixed by removing `^` from
`"@segment/analytics-react-native-plugin-mixpanel": "^0.2.3"`
to 
`"@segment/analytics-react-native-plugin-mixpanel": "0.2.3"`

Because "^0.2.3" will install the latest version (0.2.4) and this version will make your app crash. 
Please refer to the links below: 
https://github.com/segmentio/analytics-react-native/commit/511d6ac33d1fbe203776335c6cbc173ecfbb84b6
https://github.com/segmentio/analytics-react-native/releases?q=analytics-react-native-plugin-mixpanel&expanded=true

**Comment by oscb** [comment] 2022-11-03 23:49
Make sure you do a `pod install` for iOS or a gradle cache clean for Android after upgrading the Mixpanel plugin.

v0.2.4 upgraded the underlying Mixpanel SDK to their latest ([v2.1.0](https://github.com/mixpanel/mixpanel-react-native/releases/tag/v2.1.0)) which changed their native code and added additional native init params from what I can see.

If it still happening let us know, we might need to report this to Mixpanel.

**Comment by theonetheycallneo** [comment] 2022-11-05 21:39
We are seeing the same issue...

```
"@segment/analytics-react-native": "2.9.1",
    "@segment/analytics-react-native-plugin-mixpanel": "0.2.4",
    "@segment/sovran-react-native": "0.4.5",
    "mixpanel-react-native": "2.1.0",
    "react": "18.2.0",
    "react-native": "0.69.5",
```

Error:

```
1-05 18:38:58.425 11088 11197 E AndroidRuntime: com.facebook.react.bridge.NativeArgumentsParseException: MixpanelReactNative.initialize got 5 arguments, expected 7
11-05 18:38:58.425 11088 11197 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:349)
11-05 18:38:58.425 11088 11197 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
11-05 18:38:58.425 11088 11197 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
11-05 18:38:58.425 11088 11197 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
11-05 18:38:58.425 11088 11197 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-05 18:38:58.425 11088 11197 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
11-05 18:38:58.425 11088 11197 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
11-05 18:38:58.425 11088 11197 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
11-05 18:38:58.425 11088 11197 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
11-05 18:38:58.425 11088 11197 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by alanjcharles** [comment] 2022-11-07 17:21
Hi everyone- I am unable to reproduce this issue with a clean build using the following versions: 

`analytics-react-native`: 2.9.1
`analytics-react-native-plugin-mixpanel`" ^0.2.4
`mixpanel-react-native`: ^2.1.0 

Since we are unable to reproduce I am going to close this out for now. If you are running into issues I recommend following @oscb [advice here](https://github.com/segmentio/analytics-react-native/issues/701#issuecomment-1302800129). If that doesn't work please feel free to follow up with additional information/logs so we can continue to investigate.

**Closed by alanjcharles** 2022-11-07 17:21 UTC
Labels: bug

**Comment by theonetheycallneo** [comment] 2022-11-08 12:01
@alanjcharles Please do a release build and you will see the error from the device via logcat.

**Comment by theonetheycallneo** [comment] 2022-11-08 12:02
> Make sure you do a `pod install` for iOS or a gradle cache clean for Android after upgrading the Mixpanel plugin.
> 
> v0.2.4 upgraded the underlying Mixpanel SDK to their latest ([v2.1.0](https://github.com/mixpanel/mixpanel-react-native/releases/tag/v2.1.0)) which changed their native code and added additional native init params from what I can see.
> 
> If it still happening let us know, we might need to report this to Mixpanel.

IOS is working, it's the crash on Android for us.
